data:
  batch_size: 128
  color_jitter_strength: 0.0
  crop_scale:
    - 0.3
    - 1.0
  crop_size: 64
  image_folder: tiny-imagenet-200
  num_workers: 8
  pin_mem: true
  root_path: /content/datasets
  use_color_distortion: false
  use_gaussian_blur: false
  use_horizontal_flip: false

logging:
  folder: /content/drive/MyDrive/Mini/logs/tinyin200_vitt14_ep100_patch4/
  write_tag: jepa

mask:
  allow_overlap: false
  aspect_ratio:
    - 0.75
    - 1.5
  enc_mask_scale:
    - 0.85
    - 1.0
  min_keep: 5
  num_enc_masks: 1
  num_pred_masks: 4
  patch_size: 4           
  pred_mask_scale:
    - 0.15
    - 0.2

meta:
  copy_data: false
  load_checkpoint: true
  model_name: vit_tiny         
  pred_depth: 6
  pred_emb_dim: 192
  read_checkpoint: null
  use_bfloat16: true

optimization:
  ema:
    - 0.996
    - 1.0
  epochs: 100
  lr: 0.0008
  start_lr: 0.0001
  warmup: 10
  final_lr: 1.0e-06
  weight_decay: 0.04
  final_weight_decay: 0.4
  ipe_scale: 1.0
